# -*- conf -*-
# Amber CRT theme, gamma-2.2-inspired
# Background: #140E00
# Foreground: #FFB700

[colors-dark]
foreground = FFB700
background = 140E00

# normal ANSI
regular0 = 140E00
regular1 = 6A3C07
regular2 = 975906
regular3 = D78F00
regular4 = FFB700
regular5 = E19800
regular6 = B46C15
regular7 = FFBF5F

# bright ANSI
bright0 = 7C480F
bright1 = B46C15
bright2 = D78F00
bright3 = FFB700
bright4 = FFBF5F
bright5 = FFBB39
bright6 = E19800
bright7 = FFC57C
