# -*- conf -*-
# Amber CRT theme, gamma-2.2-inspired
# Background: #141200
# Foreground: #FFE600

[colors-dark]
foreground = FFE600
background = 141200

# normal ANSI
regular0 = 141200
regular1 = 807500
regular2 = A09400
regular3 = C3B900
regular4 = FFE600
regular5 = CFC400
regular6 = B5A900
regular7 = FFF200

# bright ANSI
bright0 = 948800
bright1 = B5A900
bright2 = CFC400
bright3 = FFE600
bright4 = FFF200
bright5 = FFEB40
bright6 = D8CC1F
bright7 = FFF6B0
