# -*- conf -*-
# Amber CRT theme, gamma-2.2-inspired
# Background: #141200
# Foreground: #FFE600

[colors-dark]
foreground = FFE600
background = 141200

# normal ANSI
regular0 = 141200
regular1 = 4E4A00
regular2 = A09400
regular3 = C3B900
regular4 = FFE600
regular5 = C3B900
regular6 = A09400
regular7 = FFF200

# bright ANSI
bright0 = 1C1B00
bright1 = A09400
bright2 = C3B900
bright3 = FFE600
bright4 = FFF200
bright5 = FFE600
bright6 = C3B900
bright7 = FFF200
